
# -*- coding: utf-8 -*-
"""table_extract_pdf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9_edGDVHv2ez5y35tu1qmAv82_2BUBG
"""

pip install ghostscript

pip install tk

pip install camelot

!pip install camelot-py[cv]

import camelot

# Use Camelot to extract tables from the PDF
tables = camelot.read_pdf("sample.pdf", pages='5')

# Print information about the tables found
print(tables)

table.export("sample.csv", f='csv', compress=True)
table[0].to_csv('sample.csv')

import camelot

# Use Camelot to extract tables from the PDF
tables = camelot.read_pdf("sample.pdf", pages='5')

# Print information about the tables found
print(tables)

# Export the first table to a CSV file (if a table is found on that page)
if tables:
    tables[0].to_csv("sample.csv")
else:
    print("No tables found on the specified page.")

# Install tabula-py
!pip install tabula-py

import tabula

# Use tabula.read_pdf to extract tables
tables = tabula.read_pdf("sample.pdf", pages=5)

tabula.convert_into("sample.pdf", "sample_tabula.csv", output_format="csv", pages=5)
